from algoritmia.problems.closures.interfaces import IDigraphTransitiveClosureFinder, IMatrixTransitiveClosureFinder
from algoritmia.problems.closures.matrixclosure import MatrixTransitiveClosureFinder, WarshallMatrixTransitiveClosureFinder, WarshallMatrixTransitiveClosureFinder2 
from algoritmia.problems.closures.digraphclosure import DigraphTransitiveClosureFinder 